### ISSUE TITLE
Assembly Bench

### ISSUE THREAD

**Issue by KitKags** [jacobEAdamson/RimworldMinifyMore#1]
Currently the Assembly Bench seems to be the only workbench that can't be minified. It would be a plus to minify that since its costly.
Haven't tested the Fabrication Bench.

Edit: Fabrication Bench can be minified

**Comment by jacobEAdamson** [comment]
I'm not sure what workbench you're referring to, is it potentially from a mod? No Assembly Bench in base game or expansions

**Comment by KitKags** [comment]
My bad. It's indeed from Vanilla Furniture Expanded - Production.

**Comment by jacobEAdamson** [comment]
Gotcha! Currently I'm not supporting any mod based buildings right now. Perhaps that'll change sometime, but I'm marking this as wontfix for the time being
